### ISSUE TITLE
BackpressureStrategy.LATEST result is different in setOnClickListener

### ISSUE THREAD

**Issue by JingweiWang** [ReactiveX/RxAndroid#432] opened 2018-06-21 12:01 UTC
I use the following code to run :

```java
findViewById(R.id.button_latest).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Flowable
                        .create(new FlowableOnSubscribe<Integer>() {
                            @Override
                            public void subscribe(FlowableEmitter<Integer> emitter) throws Exception {
                                for (int i = 0; i < 1000; i++) {
                                    emitter.onNext(i);
                                }
                            }
                        }, BackpressureStrategy.LATEST)
                        .subscribeOn(Schedulers.newThread())
                        .observeOn(AndroidSchedulers.mainThread())
                        .subscribe(new Consumer<Integer>() {
                            @Override
                            public void accept(Integer integer) throws Exception {
                                Log.d("LATEST", integer + "");
                            }
                        }, new Consumer<Throwable>() {
                            @Override
                            public void accept(Throwable throwable) throws Exception {
                                Log.d("LATEST", "Throwable: " + throwable.getMessage());
                            }
                        });
            }
        });
```

I expected result is printed out 0 to 127 and 999.

But the result of the matter is not like this.

Why is it like this？

**Comment by akarnokd** [comment] 2018-06-21 12:15
Please see the [JavaDocs of `subscribeOn`](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#subscribeOn-io.reactivex.Scheduler-).

> If there is a `create(FlowableOnSubscribe, BackpressureStrategy)` type source up in the chain, it is recommended to use `subscribeOn(scheduler, false)` instead to avoid same-pool deadlock because requests may pile up behind an eager/blocking emitter.

**Comment by JakeWharton** [comment] 2018-06-21 12:27
Closing as it's not a bug or feature request for RxAndroid. For usage questions please consider the RxJava mailing list or StackOverflow with the 'rx-java' tag in the future.

**Closed as completed by JakeWharton** 2018-06-21 12:27 UTC

**Comment by JingweiWang** [comment] 2018-06-22 03:01
@akarnokd Thank you but the result is still wrong.

**Comment by akarnokd** [comment] 2018-06-22 08:01
Please ask this question on Stackoverflow where you specify what you expected.
